### ISSUE TITLE
Bulk import tool stops on duplicate entry

### ISSUE THREAD

**Issue by kevmullet100** [v1tal3/netconfig#1]
When importing multiple devices from CSV list, the import stops at the first time a hostname or IP address is duplicated and does not continue to other devices in the list.

Error appears:
Import Devices - Result
Error with import - Error during import of devices into database

But no indication of where it stopped in the list.

**Comment by matt852** [comment]
In the newest version 1.2.0, I've run the following CSV data to test the import issue described:

```
Atest1,10.1.1.1,Switch,IOS
Atest2,10.1.1.2,Switch,IOS
Atest3,10.1.1.2,Switch,IOS
Atest3,10.1.1.4,Switch,IOS
Atest5,10.1.1.5,Switch,IOS
```

However all entries are imported successfully, and they display properly in the overall device table.

I'm marking this bug as fixed, as it is now working.  I am not sure exactly where it was fixed, but is most likely fixed due to a lot of backend code cleanup done since the time this bug was submitted.
