### ISSUE TITLE
Split project into two packages: webapp/python-cisco-client

### ISSUE THREAD

**Issue by tahajahangir** [v1tal3/netconfig#79]
It's more natural to have two packages: one for interacting with cisco devices in python, and one for a web-application that utilizes this interface.

For example, one can use the cisco-client for developing another web app, with features like user and access management. Or the cisco-client can be used in CLI or automation applications.

**Comment by matt852** [comment]
This makes sense, but not something I intend to do at this time.  I'm working on cleaning up a lot of code on the backend to support RBAC, multiple vendor network devices, etc.  I do not intend to add automation to NetConfig in the forseeable future.

If you're looking for just cisco-client code, look at NAPALM or Ansible.  Though this could be added in to work underneath the web overlay of NetConfig, I don't intend to at this time due to the massive amount of recoding that would need to be done.
